# Setup
title:        pyPRML
tagline:      python implementation for C.M.Bishop's PRML
baseurl:      ""
paginate:     1
url:        https://geek-and-art.github.io/pyPRML.github.io/

# About/contact
author:
    name:       Terence Xie
    url:        https://github.com/kid551 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge