# Setup
title: pyPRML
name: pyPRML
baseurl: "/pyPRML.github.io"
tagline: python implementation for C.M.Bishop's PRML
paginate: 1
url:        https://geek-and-art.github.io/pyPRML.github.io

# About/contact
author:
    name:       Geek and Art group
    url:        https://github.com/Geek-And-Art 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge
